# Generated by Django 5.0.7 on 2026-05-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cover_letter_version',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='cv_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
